root: true
extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:react-hooks/recommended'
  - 'plugin:cypress/recommended'
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
