export const IOP_ENVIRONMENT_CONTEXT = {
  isLightspeedEnabled: false,
  isLoading: false,
  isExportEnabled: false,
  isDisableRecEnabled: false,
  isAllowedToViewRec: true,
  displayGroupsTagsColumns: false,
  displayRuleRatings: false,
  displayRecPathways: false,
  displayExecReportLink: false,
  displayDownloadPlaybookButton: true,
  changeRemediationButtonForIop: true,
  loadChromeless: true,
  updateDocumentTitle: (name) => (document.title = name),
  getUser: () => '',
  on: () => {},
  hideGlobalFilter: () => {},
  mapGlobalFilter: () => {},
  globalFilterScope: () => {},
  requestPdf: () => Promise.resolve(),
  isProd: !/stage.*\.redhat\.com$/.test(window.location.hostname),
};
