apiVersion: v1
kind: Template
metadata:
  name: advisor-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: advisor
    spec:
      envName: ${ENV_NAME}
      title: Advisor
      deploymentRepo: https://github.com/RedHatInsights/insights-advisor-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /insights/advisor
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: "Advisor"
          expandable: true
          routes:
            - appId: "advisor"
              title: "Recommendations"
              href: "/insights/advisor/recommendations"
              product: "Red Hat Insights"
            - appId: "advisor"
              title: "Systems"
              href: "/insights/advisor/systems"
              product: "Red Hat Insights"
            - appId: "advisor"
              title: "Topics"
              href: "/insights/advisor/topics"
              product: "Red Hat Insights"
      module:
        manifestLocation: "/apps/advisor/fed-mods.json"
        modules:
          - id: "advisor"
            module: "./RootApp"
            routes:
              - pathname: /insights/advisor
              - pathname: /ansible/advisor

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/insights-advisor-frontend
