export const CRITICAL_RISK_RULES_FETCH = 'CRITICAL_RISK_RULES_FETCH';
export const HIGH_RISK_RULES_FETCH = 'HIGH_RISK_RULES_FETCH';
export const MEDIUM_RISK_RULES_FETCH = 'MEDIUM_RISK_RULES_FETCH';
export const LOW_RISK_RULES_FETCH = 'LOW_RISK_RULES_FETCH';
export const IMPACTED_SYSTEMS_FETCH = 'IMPACTED_SYSTEMS_FETCH';
export const IMPACTED_SYSTEMS_RULES_FETCH = 'IMPACTED_SYSTEMS_RULES_FETCH';
